production:
  adapter:  postgresql
  database: minecraft
  host: localhost
  username: postgres
  password: dr4g00n
development:
  adapter:  postgresql
  database: minecraft
  host: localhost
  username: postgres
  password: dr4g00n
