production:
  adapter:  postgresql
  database: minecraft
  host: 127.0.0.1
  username: postgres
  password: dr4g00n
development:
  adapter:  postgresql
  database: minecraft
  host: 127.0.0.1
  username: postgres
  password: dr4g00n
